# Generated by Django 3.1.3 on 2024-05-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTP', '0002_auto_20240524_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alg_name', models.CharField(max_length=100)),
                ('acc', models.FloatField()),
                ('pre', models.FloatField()),
                ('rec', models.FloatField()),
                ('f1', models.FloatField()),
            ],
        ),
    ]
